In [1]:
import pandas as pd
from sqlalchemy import create_engine
import numpy as np
import re
import nltk

nltk.download('stopwords')
nltk.download('wordnet')

from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk.tokenize import RegexpTokenizer
from nltk.stem.wordnet import WordNetLemmatizer

from sklearn.feature_extraction.text import CountVectorizer
import seaborn as sns

from sklearn.model_selection import GridSearchCV, train_test_split, cross_val_score

import pandas as pd
import requests 
import json 
import csv 
import time
import datetime
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.dummy import DummyClassifier 
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV, train_test_split, cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import plot_confusion_matrix, confusion_matrix
import seaborn as sns
from sklearn.metrics import accuracy_score
from sklearn.metrics import roc_auc_score
import pickle
import h5py
import tables

[nltk_data] Downloading package stopwords to /Users/rbabu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /Users/rbabu/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [2]:
# pip install --user tables
# !pip install h5py

In [3]:
jira_db_connection = create_engine('postgres://jiradb:mozhi72@192.168.2.209:5432/jiradb')


In [3]:
sql_pd = """
select pr.pname, pr.pkey|| '-' ||ji.issuenum as key, summary, ji.description 
from  jiraissue ji, project pr
WHERE ji.project = pr.id
and pr.pkey = 'PD'
order by ji.issuenum
limit 10000;

"""

In [4]:
sql_bk= """
select pr.pname, pr.pkey|| '-' ||ji.issuenum as key, summary, ji.description 
from  jiraissue ji, project pr
WHERE ji.project = pr.id
and pr.pkey = 'BK'
order by ji.issuenum
limit 10000;

"""

In [5]:
sql_ck= """
select pr.pname, pr.pkey|| '-' ||ji.issuenum as key, summary, ji.description 
from  jiraissue ji, project pr
WHERE ji.project = pr.id
and pr.pkey = 'CK'
order by ji.issuenum
limit 10000;

"""

In [6]:
sql_ml= """
select pr.pname, pr.pkey|| '-' ||ji.issuenum as key, summary, ji.description 
from  jiraissue ji, project pr
WHERE ji.project = pr.id
and pr.pkey = 'ML'
order by ji.issuenum
limit 10000;

"""

In [7]:
sql_mov= """
select pr.pname, pr.pkey|| '-' ||ji.issuenum as key, summary, ji.description 
from  jiraissue ji, project pr
WHERE ji.project = pr.id
and pr.pkey = 'MOV'
order by ji.issuenum
limit 10000;

"""

In [8]:
df_bk = pd.read_sql(sql_bk, jira_db_connection)
df_ck = pd.read_sql(sql_ck, jira_db_connection)
df_ml = pd.read_sql(sql_ml, jira_db_connection)
df_mov = pd.read_sql(sql_mov, jira_db_connection)
df_pd = pd.read_sql(sql_pd, jira_db_connection)

In [9]:
file_prefix ="Model"
datacol = 'features_fixed'

In [10]:
dataset = pd.concat([df_bk,df_ck,df_ml,df_mov,df_pd], ignore_index=True)

In [11]:
dataset.describe().T

count unique                                                top  \
pname        50000      5                                             Movies   
key          50000  50000                                            ML-5593   
summary      50000  46987  AIs from AI Dungeon 2 to sexy to funny and one...   
description  28997  18355                                                nan   

              freq  
pname        10000  
key              1  
summary        236  
description   9943

In [12]:
dataset['pname'].value_counts(normalize=True)

Movies                  0.2
Machine Learning        0.2
Cooking                 0.2
Books                   0.2
Political Discussion    0.2
Name: pname, dtype: float64

In [13]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   pname        50000 non-null  object
 1   key          50000 non-null  object
 2   summary      50000 non-null  object
 3   description  28997 non-null  object
dtypes: object(4)
memory usage: 1.5+ MB


In [14]:
dataset[dataset['description'].isnull()]

pname       key  \
0                     Books      BK-1   
1                     Books      BK-2   
4                     Books      BK-5   
6                     Books      BK-7   
13                    Books     BK-14   
...                     ...       ...   
49995  Political Discussion   PD-9996   
49996  Political Discussion   PD-9997   
49997  Political Discussion   PD-9998   
49998  Political Discussion   PD-9999   
49999  Political Discussion  PD-10000   

                                                 summary description  
0      In the Picture of Dorian Gray, do you think th...        None  
1                                                     bb        None  
4            I Forgot a book and I want to read it again        None  
6                               Good Book Recommendation        None  
13     We started an Instagram poop post page for a s...        None  
...                                                  ...         ...  
49995  How has President Trump used Implicit and Expl...        None  
49996  Is anyone else angry about how many people cou...        None  
49997  To communist living in non communist countries...        None  
49998  Do you think politics have become less of civi...        None  
49999  A conversation about gender - I would love inp...        None  

[21003 rows x 4 columns]

In [15]:
mask = dataset['description'] == 'nan'
dataset[mask]

pname      key  \
8                     Books     BK-9   
11                    Books    BK-12   
14                    Books    BK-15   
16                    Books    BK-17   
24                    Books    BK-25   
...                     ...      ...   
48729  Political Discussion  PD-8730   
49902  Political Discussion  PD-9903   
49905  Political Discussion  PD-9906   
49918  Political Discussion  PD-9919   
49920  Political Discussion  PD-9921   

                                                 summary description  
8      A Tie for First Place in the Best Nonfiction B...         nan  
11     Legendary Science Fiction Author Ben Bova Has ...         nan  
14     Tor ebook club is giving away the Wayward Chil...         nan  
16              Help Us Pick the Best Book Cover of 2020         nan  
24                Dabbing cat username and password book         nan  
...                                                  ...         ...  
48729            It’s Time we All Take Dome of The Blame         nan  
49902  Biden is not more electable than Bernie: the s...         nan  
49905  A view from outside - but from the inside - ab...         nan  
49918  Do you think people like Sean Hannity feel any...         nan  
49920  Why is Barack Obamas argument that defund the ...         nan  

[9943 rows x 4 columns]

In [16]:
dataset.fillna("", inplace=True)

In [17]:
dataset.replace(to_replace ="nan", 
                 value ="", inplace=True) 

In [18]:
dataset[dataset.isna().any(axis=1)]

Empty DataFrame
Columns: [pname, key, summary, description]
Index: []

In [19]:
mask = dataset['description'] == 'nan'
dataset[mask]

Empty DataFrame
Columns: [pname, key, summary, description]
Index: []

In [20]:
dataset['space'] = " "

In [21]:
dataset['features'] = dataset['summary']+ dataset['space'] + dataset['description']

In [22]:
dataset['features_fixed'] = [re.sub(r"[^A-Za-z0-9\'.,]+", ' ', data).strip().lower() for data in dataset['features']]

In [28]:
dataset['label'] = dataset['pname'].map({'Books' : 0,
                                        'Cooking' : 1,
                                        'Machine Learning' : 2,
                                        'Movies' : 3,
                                        'Political Discussion' :4})

In [29]:
mask = dataset['key'] == 'PD-9919'
dataset[mask]

pname      key  \
49918  Political Discussion  PD-9919   

                                                 summary description space  \
49918  Do you think people like Sean Hannity feel any...                     

                                                features  \
49918  Do you think people like Sean Hannity feel any...   

                                          features_fixed  label  
49918  do you think people like sean hannity feel any...      4

In [65]:
# h5File = "fromdf.h5";
# dataset.to_hdf(h5File, "./data");
dataset.to_pickle("./data/dataset_df.pkl")


In [64]:
freq = pd.Series(' '.join(map(str, dataset[datacol])).split()).value_counts()[:10]
freq

the    109793
i       74730
to      70552
a       66841
and     66751
of      53471
in      37604
it      32958
for     31624
is      31407
dtype: int64

In [31]:
freq1 =  pd.Series(' '.join(map(str,dataset 
         [datacol])).split()).value_counts()[-10:]
freq1

clapack            1
scandinavia,       1
underestimated,    1
harles             1
tada,              1
...etc             1
dumezweni          1
marbling,          1
phylo              1
creosote           1
dtype: int64

In [32]:
X = dataset['features_fixed']
y = dataset['label']

In [33]:
X.head()

0    in the picture of dorian gray, do you think th...
1                                                   bb
2    need some advice from book experts i got a lot...
3    can we talk about the invisible life of addie ...
4          i forgot a book and i want to read it again
Name: features_fixed, dtype: object

In [34]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: label, dtype: int64

In [35]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 22)

In [36]:
pipe = make_pipeline(CountVectorizer(stop_words = 'english', max_features = 1000),
                    StandardScaler(with_mean = False),
                    LogisticRegression(multi_class='ovr'))

In [37]:
pipe.fit(X_train, y_train)

/Users/rbabu/opt/anaconda3/envs/sql/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/rbabu/opt/anaconda3/envs/sql/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linea

Pipeline(steps=[('countvectorizer',
                 CountVectorizer(max_features=1000, stop_words='english')),
                ('standardscaler', StandardScaler(with_mean=False)),
                ('logisticregression', LogisticRegression(multi_class='ovr'))])

In [38]:
pipe.score(X_train, y_train)

0.8694933333333333

In [39]:
pipe.score(X_test, y_test)

0.84312

In [40]:
y_lr_preds = pipe.predict(X_test)

In [41]:
conf_mat = confusion_matrix(y_test, y_lr_preds)
print(conf_mat)

[[1887   24   56  172  339]
 [  44 2316   18   48   63]
 [  76    5 2178   84  195]
 [ 133   22   47 1955  352]
 [  97   14   48  124 2203]]


In [42]:
df_y_test = pd.DataFrame(y_test)
df_y_test.head()

label
20920      2
21590      2
21586      2
41939      4
25260      2

In [45]:
df_y_predict = pd.DataFrame(y_lr_preds, columns=['label'])
df_y_predict.head()

label
0      2
1      2
2      2
3      4
4      2

In [46]:
count = 0
total = 0
for i, (x, y) in enumerate(zip(df_y_test.label, df_y_predict.label)):
    total = total +1 
    if (str(x) != str(y) ):
        count = count +1
        print(f'index:{i}, actual:{x}, predicted: {y}')
        
print(f" out of {total}, {count} predicted wrong")

index:7, actual:0, predicted: 2
index:13, actual:2, predicted: 4
index:20, actual:3, predicted: 4
index:41, actual:3, predicted: 4
index:46, actual:0, predicted: 4
index:58, actual:3, predicted: 0
index:80, actual:2, predicted: 4
index:84, actual:3, predicted: 1
index:87, actual:2, predicted: 0
index:93, actual:3, predicted: 4
index:100, actual:3, predicted: 4
index:105, actual:0, predicted: 3
index:108, actual:1, predicted: 4
index:126, actual:2, predicted: 4
index:129, actual:3, predicted: 4
index:131, actual:0, predicted: 4
index:132, actual:3, predicted: 4
index:133, actual:0, predicted: 4
index:139, actual:2, predicted: 4
index:151, actual:3, predicted: 4
index:160, actual:0, predicted: 4
index:163, actual:0, predicted: 4
index:164, actual:1, predicted: 3
index:166, actual:0, predicted: 4
index:175, actual:3, predicted: 4
index:190, actual:3, predicted: 4
index:208, actual:0, predicted: 4
index:214, actual:4, predicted: 3
index:216, actual:0, predicted: 3
index:226, actual:0, pred

In [47]:
 pipe.predict(['I died a little After I saw how my mom defrosting meat'])

array([1])

In [48]:
Pkl_Filename = "Pickle_LR_Model.pkl"  

with open(Pkl_Filename, 'wb') as file:  
    pickle.dump(pipe, file)

In [49]:
with open(Pkl_Filename, 'rb') as file:  
    model_imported = pickle.load(file)

In [50]:
model_imported

Pipeline(steps=[('countvectorizer',
                 CountVectorizer(max_features=1000, stop_words='english')),
                ('standardscaler', StandardScaler(with_mean=False)),
                ('logisticregression', LogisticRegression(multi_class='ovr'))])

In [51]:
 model_imported.predict(['I died a little After I saw how my mom defrosting meat'])

array([1])